Adding a defensive null check.
Sending e-mails to: kk@kohsuke.org null
ERROR: 250 OK id=1WPzqg-0007nL-OR

com.sun.mail.smtp.SMTPSendFailedException: 250 OK id=1WPzqg-0007nL-OR
;
  nested exception is:
    com.sun.mail.smtp.SMTPAddressFailedException: 501 <null>: recipient address must contain a domain

    at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1112)
    at javax.mail.Transport.send0(Transport.java:195)
    at javax.mail.Transport.send(Transport.java:124)
    at hudson.tasks.MailSender.execute(MailSender.java:116)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.cleanUp(MavenModuleSetBuild.java:1038)
    at hudson.model.Run.execute(Run.java:1710)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:509)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:246)
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 501 <null>: recipient address must contain a domain

    at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1686)
    at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1098)
    ... 8 more